In [15]:
import pandas as pd
import matplotlib.pyplot as plt
#lendo o começo do arquivo csv
ler_csv = pd.read_csv(r'C:\Users\nanda\OneDrive\Documentos\estudo\analise de dados\orcamento_despesa-2025\dados\bruto\2025_OrcamentoDespesa.csv', encoding='latin-1', sep=';')

ler_csv.head()

,EXERCÍCIO,CÓDIGO ÓRGÃO SUPERIOR,NOME ÓRGÃO SUPERIOR,CÓDIGO ÓRGÃO SUBORDINADO,NOME ÓRGÃO SUBORDINADO,CÓDIGO UNIDADE ORÇAMENTÁRIA,NOME UNIDADE ORÇAMENTÁRIA,CÓDIGO FUNÇÃO,NOME FUNÇÃO,CÓDIGO SUBFUNÇÃO,...,NOME CATEGORIA ECONÔMICA,CÓDIGO GRUPO DE DESPESA,NOME GRUPO DE DESPESA,CÓDIGO ELEMENTO DE DESPESA,NOME ELEMENTO DE DESPESA,ORÇAMENTO INICIAL (R$),ORÇAMENTO ATUALIZADO (R$),ORÇAMENTO EMPENHADO (R$),ORÇAMENTO REALIZADO (R$),% REALIZADO DO ORÇAMENTO (COM RELAÇÃO AO ORÇAMENTO ATUALIZADO)
0,2025,13000,Justiça Militar,13000,Justiça Militar - Unidades com vínculo direto,13101,JUSTICA MILITAR,2,Judiciária,61,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,39,Outros Serviços de Terceiros - Pessoa Jurídica,"0,00","0,00","185311,65","24282,78","0,00%"
1,2025,20000,Presidência da República,20101,Presidência da República,20101,PRESIDENCIA DA REPUBLICA,4,Administração,122,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,33,Passagens e Despesas com Locomoção,"3453902,73","3453902,73","3453902,73","2574342,48","74,53%"
2,2025,20000,Presidência da República,20101,Presidência da República,20118,AGENCIA BRASILEIRA DE INTELIGENCIA - ABIN,9,Previdência social,272,...,DESPESAS CORRENTES,1,Pessoal e Encargos Sociais,1,"Aposentadorias, Reserva Remunerada e Reformas","257155176,61","257155176,61","256492075,11","235588579,37","91,61%"
3,2025,20000,Presidência da República,20101,Presidência da República,20101,PRESIDENCIA DA REPUBLICA,28,Encargos especiais,846,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,0,Não informado,"5400370,00","0,00","0,00","0,00","0,00%"
4,2025,20000,Presidência da República,20101,Presidência da República,20118,AGENCIA BRASILEIRA DE INTELIGENCIA - ABIN,6,Segurança pública,122,...,DESPESAS CORRENTES,1,Pessoal e Encargos Sociais,11,Vencimentos e Vantagens Fixas - Pessoal Civil,"349061273,02","349061273,02","348284454,67","309882124,46","88,78%"

In [16]:
#ler 100 linhas do arquivo csv
print(ler_csv.head(100))

    EXERCÍCIO  CÓDIGO ÓRGÃO SUPERIOR       NOME ÓRGÃO SUPERIOR  \
0        2025                  13000           Justiça Militar
1        2025                  20000  Presidência da República
2        2025                  20000  Presidência da República
3        2025                  20000  Presidência da República
4        2025                  20000  Presidência da República
..        ...                    ...                       ...
95       2025                  20000  Presidência da República
96       2025                  20000  Presidência da República
97       2025                  20000  Presidência da República
98       2025                  20000  Presidência da República
99       2025                  20000  Presidência da República

    CÓDIGO ÓRGÃO SUBORDINADO                         NOME ÓRGÃO SUBORDINADO  \
0                      13000  Justiça Militar - Unidades com vínculo direto
1                      20101                       Presidência da República
2                      20101                       Presidência da República
3                      20101                       Presidência da República
4                      20101                       Presidência da República
..                       ...                                            ...
95                     20101                       Presidência da República
96                     20101                       Presidência da República
97                     20101                       Presidência da República
98                     20415                  Empresa Brasil de Comunicação
99                     20101                       Presidência da República

    CÓDIGO UNIDADE ORÇAMENTÁRIA                  NOME UNIDADE ORÇAMENTÁRIA  \
0                         13101                            JUSTICA MILITAR
1                         20101                   PRESIDENCIA DA REPUBLICA
2                         20118  AGENCIA BRASILEIRA DE INTELIGENCIA - ABIN
3                         20101                   PRESIDENCIA DA REPUBLICA
4                         20118  AGENCIA BRASILEIRA DE INTELIGENCIA - ABIN
..                          ...                                        ...
95                        20118  AGENCIA BRASILEIRA DE INTELIGENCIA - ABIN
96                        20118  AGENCIA BRASILEIRA DE INTELIGENCIA - ABIN
97                        20101                   PRESIDENCIA DA REPUBLICA
98                        20415              EMPRESA BRASIL DE COMUNICACAO
99                        20118  AGENCIA BRASILEIRA DE INTELIGENCIA - ABIN

    CÓDIGO FUNÇÃO            NOME FUNÇÃO  CÓDIGO SUBFUNÇÃO  ...  \
0               2             Judiciária                61  ...
1               4          Administração               122  ...
2               9     Previdência social               272  ...
3              28     Encargos especiais               846  ...
4               6      Segurança pública               122  ...
..            ...                    ...               ...  ...
95              4          Administração               122  ...
96              4          Administração               183  ...
97             14  Direitos da cidadania               422  ...
98              4          Administração               122  ...
99              4          Administração               183  ...

   NOME CATEGORIA ECONÔMICA  CÓDIGO GRUPO DE DESPESA  \
0        DESPESAS CORRENTES                        3
1        DESPESAS CORRENTES                        3
2        DESPESAS CORRENTES                        1
3        DESPESAS CORRENTES                        3
4        DESPESAS CORRENTES                        1
..                      ...                      ...
95       DESPESAS CORRENTES                        3
96      DESPESAS DE CAPITAL                        4
97       DESPESAS CORRENTES                        3
98       DESPESAS CORRENTES                        3
99       DESPESAS CORRENTES                        3

         NOME GRUPO DE DESPESA CÓDIGO ELEMENTO DE DESPESA  \
0    Outras Despesas Correntes                         39
1    Outras Despesas Correntes                         33
2   Pessoal e Encargos Sociais                          1
3    Outras Despesas Correntes                          0
4   Pessoal e Encargos Sociais                         11
..                         ...                        ...
95   Outras Despesas Correntes                         92
96               Investimentos                          0
97   Outras Despesas Correntes                         92
98   Outras Despesas Correntes                          0
99   Outras Despesas Correntes                         14

                          NOME ELEMENTO DE DESPESA  ORÇAMENTO INICIAL (R$)  \
0   Outros Serviços de Terceiros - Pessoa Jurídica                    0,00
1               Passagens e Despesas com Locomoção              3453902,73
2    Aposentadorias, Reserva Remunerada e Reformas            257155176,61
3                                    Não informado              5400370,00
4    Vencimentos e Vantagens Fixas - Pessoal Civil            349061273,02
..                                             ...                     ...
95               Despesas de Exercícios Anteriores                10606,37
96                                   Não informado              3800192,08
97               Despesas de Exercícios Anteriores                24139,75
98                                   Não informado                -2000,00
99                                 Diárias - Civil              1064048,92

   ORÇAMENTO ATUALIZADO (R$)  ORÇAMENTO EMPENHADO (R$)  \
0                       0,00                 185311,65
1                 3453902,73                3453902,73
2               257155176,61              256492075,11
3                       0,00                      0,00
4               349061273,02              348284454,67
..                       ...                       ...
95                  10606,37                   8606,37
96                      1,08                      0,00
97                  24139,75                  24139,75
98                      0,00                      0,00
99                1064048,92                1064048,92

   ORÇAMENTO REALIZADO (R$)  \
0                  24282,78
1                2574342,48
2              235588579,37
3                      0,00
4              309882124,46
..                      ...
95                  5886,73
96                     0,00
97                 24139,75
98                     0,00
99               1064048,92

    % REALIZADO DO ORÇAMENTO (COM RELAÇÃO AO ORÇAMENTO ATUALIZADO)
0                                               0,00%
1                                              74,53%
2                                              91,61%
3                                               0,00%
4                                              88,78%
..                                                ...
95                                             55,50%
96                                              0,00%
97                                            100,00%
98                                              0,00%
99                                            100,00%

[100 rows x 26 columns]

In [17]:
#vendo a estrutura do csv
ler_csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 26160 entries, 0 to 26159
Data columns (total 26 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   EXERCÍCIO                                                       26160 non-null  int64
 1   CÓDIGO ÓRGÃO SUPERIOR                                           26160 non-null  int64
 2   NOME ÓRGÃO SUPERIOR                                             26160 non-null  str
 3   CÓDIGO ÓRGÃO SUBORDINADO                                        26160 non-null  int64
 4   NOME ÓRGÃO SUBORDINADO                                          26160 non-null  str
 5   CÓDIGO UNIDADE ORÇAMENTÁRIA                                     26160 non-null  int64
 6   NOME UNIDADE ORÇAMENTÁRIA                                       26160 non-null  str
 7   CÓDIGO FUNÇÃO                                                   26160 non-null  int64
 8   NOME FUNÇÃO                                                     26160 non-null  str
 9   CÓDIGO SUBFUNÇÃO                                                26160 non-null  int64
 10  NOME SUBFUNÇÃO                                                  26160 non-null  str
 11  CÓDIGO PROGRAMA ORÇAMENTÁRIO                                    26160 non-null  int64
 12  NOME PROGRAMA ORÇAMENTÁRIO                                      26160 non-null  str
 13  CÓDIGO AÇÃO                                                     26160 non-null  str
 14  NOME AÇÃO                                                       26160 non-null  str
 15  CÓDIGO CATEGORIA ECONÔMICA                                      26160 non-null  int64
 16  NOME CATEGORIA ECONÔMICA                                        26160 non-null  str
 17  CÓDIGO GRUPO DE DESPESA                                         26160 non-null  int64
 18  NOME GRUPO DE DESPESA                                           26160 non-null  str
 19  CÓDIGO ELEMENTO DE DESPESA                                      26160 non-null  int64
 20  NOME ELEMENTO DE DESPESA                                        26160 non-null  str
 21  ORÇAMENTO INICIAL (R$)                                          26160 non-null  str
 22  ORÇAMENTO ATUALIZADO (R$)                                       26160 non-null  str
 23  ORÇAMENTO EMPENHADO (R$)                                        26160 non-null  str
 24  ORÇAMENTO REALIZADO (R$)                                        26160 non-null  str
 25  % REALIZADO DO ORÇAMENTO (COM RELAÇÃO AO ORÇAMENTO ATUALIZADO)  26160 non-null  str
dtypes: int64(10), str(16)
memory usage: 5.2 MB

In [18]:
#saber as colunas do csv
ler_csv.columns

Index(['EXERCÍCIO', 'CÓDIGO ÓRGÃO SUPERIOR', 'NOME ÓRGÃO SUPERIOR',
       'CÓDIGO ÓRGÃO SUBORDINADO', 'NOME ÓRGÃO SUBORDINADO',
       'CÓDIGO UNIDADE ORÇAMENTÁRIA', 'NOME UNIDADE ORÇAMENTÁRIA',
       'CÓDIGO FUNÇÃO', 'NOME FUNÇÃO', 'CÓDIGO SUBFUNÇÃO', 'NOME SUBFUNÇÃO',
       'CÓDIGO PROGRAMA ORÇAMENTÁRIO', 'NOME PROGRAMA ORÇAMENTÁRIO',
       'CÓDIGO AÇÃO', 'NOME AÇÃO', 'CÓDIGO CATEGORIA ECONÔMICA',
       'NOME CATEGORIA ECONÔMICA', 'CÓDIGO GRUPO DE DESPESA',
       'NOME GRUPO DE DESPESA', 'CÓDIGO ELEMENTO DE DESPESA',
       'NOME ELEMENTO DE DESPESA', 'ORÇAMENTO INICIAL (R$)',
       'ORÇAMENTO ATUALIZADO (R$)', 'ORÇAMENTO EMPENHADO (R$)',
       'ORÇAMENTO REALIZADO (R$)',
       '% REALIZADO DO ORÇAMENTO (COM RELAÇÃO AO ORÇAMENTO ATUALIZADO)'],
      dtype='str')

In [19]:
#ver quantidade de valores não nulos por coluna
ler_csv.notnull()

,EXERCÍCIO,CÓDIGO ÓRGÃO SUPERIOR,NOME ÓRGÃO SUPERIOR,CÓDIGO ÓRGÃO SUBORDINADO,NOME ÓRGÃO SUBORDINADO,CÓDIGO UNIDADE ORÇAMENTÁRIA,NOME UNIDADE ORÇAMENTÁRIA,CÓDIGO FUNÇÃO,NOME FUNÇÃO,CÓDIGO SUBFUNÇÃO,...,NOME CATEGORIA ECONÔMICA,CÓDIGO GRUPO DE DESPESA,NOME GRUPO DE DESPESA,CÓDIGO ELEMENTO DE DESPESA,NOME ELEMENTO DE DESPESA,ORÇAMENTO INICIAL (R$),ORÇAMENTO ATUALIZADO (R$),ORÇAMENTO EMPENHADO (R$),ORÇAMENTO REALIZADO (R$),% REALIZADO DO ORÇAMENTO (COM RELAÇÃO AO ORÇAMENTO ATUALIZADO)
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26155,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
26156,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
26157,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
26158,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
26159,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [20]:
#tirar os valores duplicados do csv
ler_csv = ler_csv.drop_duplicates()
ler_csv.head(900)
# Salva o csv 'ler_csv' em um novo arquivo
ler_csv.to_csv('../dados/bruto/2025_OrcamentoDespesa_semduplicadas.csv', index=False, sep=';', encoding='latin-1')

In [ ]:
#vizualizar os valores duplicados do csv (duplicado não significa que está errado, pode ser que haja mais de uma linha com os mesmos dados)
print(ler_csv[ler_csv.duplicated(keep=False)])

       EXERCÍCIO  CÓDIGO ÓRGÃO SUPERIOR  \
16977       2025                  36000
16991       2025                  36000
19279       2025                  44000
19300       2025                  44000
25819       2025                  81000
25845       2025                  81000
26103       2025                  84000
26115       2025                  84000

                                  NOME ÓRGÃO SUPERIOR  \
16977                             Ministério da Saúde
16991                             Ministério da Saúde
19279  Ministério do Meio Ambiente e Mudança do Clima
19300  Ministério do Meio Ambiente e Mudança do Clima
25819     Ministério dos Direitos Humanos e Cidadania
25845     Ministério dos Direitos Humanos e Cidadania
26103                  Ministério dos Povos Indígenas
26115                  Ministério dos Povos Indígenas

       CÓDIGO ÓRGÃO SUBORDINADO  \
16977                     36211
16991                     36211
19279                     44000
19300                     44000
25819                     30914
25845                     30914
26103                     30202
26115                     30202

                                  NOME ÓRGÃO SUBORDINADO  \
16977                         Fundação Nacional de Saúde
16991                         Fundação Nacional de Saúde
19279  Ministério do Meio Ambiente e Mudança do Clima...
19300  Ministério do Meio Ambiente e Mudança do Clima...
25819                            Fundo Nacional do Idoso
25845                            Fundo Nacional do Idoso
26103              Fundação Nacional dos Povos Indígenas
26115              Fundação Nacional dos Povos Indígenas

       CÓDIGO UNIDADE ORÇAMENTÁRIA  \
16977                        36211
16991                        36211
19279                        44101
19300                        44101
25819                        81902
25845                        81902
26103                        84201
26115                        84201

                         NOME UNIDADE ORÇAMENTÁRIA  CÓDIGO FUNÇÃO  \
16977                   FUNDACAO NACIONAL DE SAUDE             10
16991                   FUNDACAO NACIONAL DE SAUDE             10
19279  MINIST. DO MEIO AMBIENTE E MUDANCA DO CLIMA             18
19300  MINIST. DO MEIO AMBIENTE E MUDANCA DO CLIMA             18
25819                FUNDO NACIONAL DO IDOSO - FNI             14
25845                FUNDO NACIONAL DO IDOSO - FNI             14
26103        FUNDACAO NACIONAL DOS POVOS INDIGENAS             14
26115        FUNDACAO NACIONAL DOS POVOS INDIGENAS             14

                 NOME FUNÇÃO  CÓDIGO SUBFUNÇÃO  ... NOME CATEGORIA ECONÔMICA  \
16977                  Saúde               512  ...      DESPESAS DE CAPITAL
16991                  Saúde               512  ...      DESPESAS DE CAPITAL
19279       Gestão ambiental               128  ...      DESPESAS DE CAPITAL
19300       Gestão ambiental               128  ...      DESPESAS DE CAPITAL
25819  Direitos da cidadania               241  ...       DESPESAS CORRENTES
25845  Direitos da cidadania               241  ...       DESPESAS CORRENTES
26103  Direitos da cidadania               423  ...       DESPESAS CORRENTES
26115  Direitos da cidadania               423  ...       DESPESAS CORRENTES

       CÓDIGO GRUPO DE DESPESA      NOME GRUPO DE DESPESA  \
16977                        4              Investimentos
16991                        4              Investimentos
19279                        4              Investimentos
19300                        4              Investimentos
25819                        3  Outras Despesas Correntes
25845                        3  Outras Despesas Correntes
26103                        3  Outras Despesas Correntes
26115                        3  Outras Despesas Correntes

      CÓDIGO ELEMENTO DE DESPESA NOME ELEMENTO DE DESPESA  \
16977                          0            Não informado
16991                          0            Não informado
19279                          0            Não informado
19300                          0            Não informado
25819                          0            Não informado
25845                          0            Não informado
26103                          0            Não informado
26115                          0            Não informado

       ORÇAMENTO INICIAL (R$) ORÇAMENTO ATUALIZADO (R$)  \
16977               500000,00                      0,00
16991               500000,00                      0,00
19279               400000,00                      0,00
19300               400000,00                      0,00
25819                    1,00                      1,00
25845                    1,00                      1,00
26103               200000,00                      0,00
26115               200000,00                      0,00

       ORÇAMENTO EMPENHADO (R$) ORÇAMENTO REALIZADO (R$)  \
16977                      0,00                     0,00
16991                      0,00                     0,00
19279                      0,00                     0,00
19300                      0,00                     0,00
25819                      0,00                     0,00
25845                      0,00                     0,00
26103                      0,00                     0,00
26115                      0,00                     0,00

       % REALIZADO DO ORÇAMENTO (COM RELAÇÃO AO ORÇAMENTO ATUALIZADO)
16977                                              0,00%
16991                                              0,00%
19279                                              0,00%
19300                                              0,00%
25819                                              0,00%
25845                                              0,00%
26103                                              0,00%
26115                                              0,00%

[8 rows x 26 columns]

In [ ]:
# Retorna todas as linhas que são cópias de uma anterior nos seus indexes, ou seja, todas as linhas duplicadas, incluindo a primeira ocorrência.
duplicados_todos = ler_csv[ler_csv.duplicated(keep=False)]
print(duplicados_todos)

Empty DataFrame
Columns: [EXERCÍCIO, CÓDIGO ÓRGÃO SUPERIOR, NOME ÓRGÃO SUPERIOR, CÓDIGO ÓRGÃO SUBORDINADO, NOME ÓRGÃO SUBORDINADO, CÓDIGO UNIDADE ORÇAMENTÁRIA, NOME UNIDADE ORÇAMENTÁRIA, CÓDIGO FUNÇÃO, NOME FUNÇÃO, CÓDIGO SUBFUNÇÃO, NOME SUBFUNÇÃO, CÓDIGO PROGRAMA ORÇAMENTÁRIO, NOME PROGRAMA ORÇAMENTÁRIO, CÓDIGO AÇÃO, NOME AÇÃO, CÓDIGO CATEGORIA ECONÔMICA, NOME CATEGORIA ECONÔMICA, CÓDIGO GRUPO DE DESPESA, NOME GRUPO DE DESPESA, CÓDIGO ELEMENTO DE DESPESA, NOME ELEMENTO DE DESPESA, ORÇAMENTO INICIAL (R$), ORÇAMENTO ATUALIZADO (R$), ORÇAMENTO EMPENHADO (R$), ORÇAMENTO REALIZADO (R$), % REALIZADO DO ORÇAMENTO (COM RELAÇÃO AO ORÇAMENTO ATUALIZADO)]
Index: []

[0 rows x 26 columns]

In [21]:
#tirar valores nulos do csv
ler_csv = ler_csv.dropna()
ler_csv.head(900)

,EXERCÍCIO,CÓDIGO ÓRGÃO SUPERIOR,NOME ÓRGÃO SUPERIOR,CÓDIGO ÓRGÃO SUBORDINADO,NOME ÓRGÃO SUBORDINADO,CÓDIGO UNIDADE ORÇAMENTÁRIA,NOME UNIDADE ORÇAMENTÁRIA,CÓDIGO FUNÇÃO,NOME FUNÇÃO,CÓDIGO SUBFUNÇÃO,...,NOME CATEGORIA ECONÔMICA,CÓDIGO GRUPO DE DESPESA,NOME GRUPO DE DESPESA,CÓDIGO ELEMENTO DE DESPESA,NOME ELEMENTO DE DESPESA,ORÇAMENTO INICIAL (R$),ORÇAMENTO ATUALIZADO (R$),ORÇAMENTO EMPENHADO (R$),ORÇAMENTO REALIZADO (R$),% REALIZADO DO ORÇAMENTO (COM RELAÇÃO AO ORÇAMENTO ATUALIZADO)
0,2025,13000,Justiça Militar,13000,Justiça Militar - Unidades com vínculo direto,13101,JUSTICA MILITAR,2,Judiciária,61,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,39,Outros Serviços de Terceiros - Pessoa Jurídica,"0,00","0,00","185311,65","24282,78","0,00%"
1,2025,20000,Presidência da República,20101,Presidência da República,20101,PRESIDENCIA DA REPUBLICA,4,Administração,122,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,33,Passagens e Despesas com Locomoção,"3453902,73","3453902,73","3453902,73","2574342,48","74,53%"
2,2025,20000,Presidência da República,20101,Presidência da República,20118,AGENCIA BRASILEIRA DE INTELIGENCIA - ABIN,9,Previdência social,272,...,DESPESAS CORRENTES,1,Pessoal e Encargos Sociais,1,"Aposentadorias, Reserva Remunerada e Reformas","257155176,61","257155176,61","256492075,11","235588579,37","91,61%"
3,2025,20000,Presidência da República,20101,Presidência da República,20101,PRESIDENCIA DA REPUBLICA,28,Encargos especiais,846,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,0,Não informado,"5400370,00","0,00","0,00","0,00","0,00%"
4,2025,20000,Presidência da República,20101,Presidência da República,20118,AGENCIA BRASILEIRA DE INTELIGENCIA - ABIN,6,Segurança pública,122,...,DESPESAS CORRENTES,1,Pessoal e Encargos Sociais,11,Vencimentos e Vantagens Fixas - Pessoal Civil,"349061273,02","349061273,02","348284454,67","309882124,46","88,78%"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,2025,24000,"Ministério da Ciência, Tecnologia e Inovação",24901,Fundo Nacional de Desenvolvimento Científico e...,24901,FUNDO NACIONAL DE DESENV.CIENT.E TECNOLOGICO,19,Ciência e Tecnologia,572,...,DESPESAS DE CAPITAL,4,Investimentos,20,Auxílio Financeiro a Pesquisadores,"745606,46","745606,46","745606,46","0,00","0,00%"
896,2025,24000,"Ministério da Ciência, Tecnologia e Inovação",24000,"Ministério da Ciência, Tecnologia e Inovação -...",24101,"MINIST. DA CIENCIA, TECNOLOGIA E INOVOVACAO",19,Ciência e Tecnologia,572,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,30,Material de Consumo,"53899,98","53899,98","53899,98","53677,64","99,59%"
897,2025,24000,"Ministério da Ciência, Tecnologia e Inovação",20402,Agência Espacial Brasileira,24205,AGENCIA ESPACIAL BRASILEIRA - AEB,19,Ciência e Tecnologia,572,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,0,Não informado,"3498557,58","6,58","0,00","0,00","0,00%"
898,2025,24000,"Ministério da Ciência, Tecnologia e Inovação",20301,Comissão Nacional de Energia Nuclear,24204,COMISSAO NACIONAL DE ENERGIA NUCLEAR - CNEN,19,Ciência e Tecnologia,125,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,92,Despesas de Exercícios Anteriores,"81292,28","81292,28","81292,28","81292,28","100,00%"
899,2025,24000,"Ministério da Ciência, Tecnologia e Inovação",24000,"Ministério da Ciência, Tecnologia e Inovação -...",24101,"MINIST. DA CIENCIA, TECNOLOGIA E INOVOVACAO",19,Ciência e Tecnologia,571,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,41,Contribuições,"272000,00","272000,00","272000,00","0,00","0,00%"

In [33]:
#loop criado para padronizar as colunas de orçamento de tipo string para o tipo float
colunas_dinheiro = ['ORÇAMENTO INICIAL (R$)', 'ORÇAMENTO ATUALIZADO (R$)', 'ORÇAMENTO EMPENHADO (R$)', 'ORÇAMENTO REALIZADO (R$)']

for coluna in range(len(colunas_dinheiro)):
    ler_csv[colunas_dinheiro[coluna]] = ler_csv[colunas_dinheiro[coluna]].astype(str).replace('.', '', regex=False).replace(',', '.', regex=False).astype(float)
    print(ler_csv[colunas_dinheiro[coluna]].head())
ler_csv.to_csv(r'C:\Users\nanda\OneDrive\Documentos\estudo\analise de dados\orcamento_despesa-2025\dados\bruto\2025_OrcamentoDespesa_semduplicadas.csv', index=False, sep=';', encoding='utf-8-sig')

0           0.00
1     3453902.73
2   257155176.61
3     5400370.00
4   349061273.02
Name: ORÇAMENTO INICIAL (R$), dtype: float64
0           0.00
1     3453902.73
2   257155176.61
3           0.00
4   349061273.02
Name: ORÇAMENTO ATUALIZADO (R$), dtype: float64
0      185311.65
1     3453902.73
2   256492075.11
3           0.00
4   348284454.67
Name: ORÇAMENTO EMPENHADO (R$), dtype: float64
0       24282.78
1     2574342.48
2   235588579.37
3           0.00
4   309882124.46
Name: ORÇAMENTO REALIZADO (R$), dtype: float64

In [35]:
#loop criado para padronizar as colunas de orçamento de tipo string para ser tudo maiúsculo
colunas_string = ['NOME ÓRGÃO SUPERIOR', 'NOME ÓRGÃO SUBORDINADO', 'NOME UNIDADE ORÇAMENTÁRIA','NOME FUNÇÃO','NOME SUBFUNÇÃO', 'NOME PROGRAMA ORÇAMENTÁRIO', 'NOME AÇÃO', 'NOME CATEGORIA ECONÔMICA', 'NOME GRUPO DE DESPESA','NOME ELEMENTO DE DESPESA']
for coluna in range(len(colunas_string)):
    ler_csv[colunas_string[coluna]] = ler_csv[colunas_string[coluna]].astype(str).str.upper()
    print(ler_csv[colunas_string[coluna]].head())
#usando a formatação utf-8-sig para evitar problemas ao abrir o arquivo csv em outros programas, como o Excel, que podem não reconhecer corretamente os caracteres acentuados.
ler_csv.to_csv(r'C:\Users\nanda\OneDrive\Documentos\estudo\analise de dados\orcamento_despesa-2025\dados\bruto\2025_OrcamentoDespesa_semduplicadas.csv', index=False, sep=';', encoding='utf-8-sig')

0             JUSTIÇA MILITAR
1    PRESIDÊNCIA DA REPÚBLICA
2    PRESIDÊNCIA DA REPÚBLICA
3    PRESIDÊNCIA DA REPÚBLICA
4    PRESIDÊNCIA DA REPÚBLICA
Name: NOME ÓRGÃO SUPERIOR, dtype: str
0    JUSTIÇA MILITAR - UNIDADES COM VÍNCULO DIRETO
1                         PRESIDÊNCIA DA REPÚBLICA
2                         PRESIDÊNCIA DA REPÚBLICA
3                         PRESIDÊNCIA DA REPÚBLICA
4                         PRESIDÊNCIA DA REPÚBLICA
Name: NOME ÓRGÃO SUBORDINADO, dtype: str
0                              JUSTICA MILITAR
1                     PRESIDENCIA DA REPUBLICA
2    AGENCIA BRASILEIRA DE INTELIGENCIA - ABIN
3                     PRESIDENCIA DA REPUBLICA
4    AGENCIA BRASILEIRA DE INTELIGENCIA - ABIN
Name: NOME UNIDADE ORÇAMENTÁRIA, dtype: str
0            JUDICIÁRIA
1         ADMINISTRAÇÃO
2    PREVIDÊNCIA SOCIAL
3    ENCARGOS ESPECIAIS
4     SEGURANÇA PÚBLICA
Name: NOME FUNÇÃO, dtype: str
0                      AÇÃO JUDICIÁRIA
1                  ADMINISTRAÇÃO GERAL
2    PREVIDÊNCIA DO REGIME ESTATUTÁRIO
3            OUTROS ENCARGOS ESPECIAIS
4                  ADMINISTRAÇÃO GERAL
Name: NOME SUBFUNÇÃO, dtype: str
0    PROGRAMA DE GESTAO E MANUTENCAO DO PODER JUDIC...
1    RECONSTRUCAO, AMPLIACAO E APROFUNDAMENTO DA PA...
2    PROGRAMA DE GESTAO E MANUTENCAO DO PODER EXECU...
3    OPERACOES ESPECIAIS: GESTAO DA PARTICIPACAO EM...
4    PROGRAMA DE GESTAO E MANUTENCAO DO PODER EXECU...
Name: NOME PROGRAMA ORÇAMENTÁRIO, dtype: str
0    PROCESSAMENTO DE CAUSAS E GESTAO ADMINISTRATIV...
1    FUNCIONAMENTO DOS CONSELHOS E COMISSOES DA PRE...
2              APOSENTADORIAS E PENSOES CIVIS DA UNIAO
3    CONTRIBUICAO A ORGANIZACAO DOS ESTADOS IBERO-A...
4                                ATIVOS CIVIS DA UNIAO
Name: NOME AÇÃO, dtype: str
0    DESPESAS CORRENTES
1    DESPESAS CORRENTES
2    DESPESAS CORRENTES
3    DESPESAS CORRENTES
4    DESPESAS CORRENTES
Name: NOME CATEGORIA ECONÔMICA, dtype: str
0     OUTRAS DESPESAS CORRENTES
1     OUTRAS DESPESAS CORRENTES
2    PESSOAL E ENCARGOS SOCIAIS
3     OUTRAS DESPESAS CORRENTES
4    PESSOAL E ENCARGOS SOCIAIS
Name: NOME GRUPO DE DESPESA, dtype: str
0    OUTROS SERVIÇOS DE TERCEIROS - PESSOA JURÍDICA
1                PASSAGENS E DESPESAS COM LOCOMOÇÃO
2     APOSENTADORIAS, RESERVA REMUNERADA E REFORMAS
3                                     NÃO INFORMADO
4     VENCIMENTOS E VANTAGENS FIXAS - PESSOAL CIVIL
Name: NOME ELEMENTO DE DESPESA, dtype: str